# Generated by Django 5.2.7 on 2025-10-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_pr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitems',
            options={'verbose_name': 'Состав заказа', 'verbose_name_plural': 'Составы заказов'},
        ),
        migrations.AddField(
            model_name='games',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
