# Generated by Django 5.2.6 on 2025-11-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_pr', '0002_alter_orderitems_options_games_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Пароль'),
        ),
    ]
