# Generated by Django 5.2.6 on 2025-11-26 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_pr', '0003_alter_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
    ]
