# Generated by Django 5.2.6 on 2025-11-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_pr', '0004_users_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='phone',
        ),
        migrations.AddField(
            model_name='games',
            name='image',
            field=models.ImageField(blank=True, default='images/default/game_default.png', null=True, upload_to='games_images/', verbose_name='Изображение игры'),
        ),
    ]
